Mappings:
  InstanceMap:
    us-east-1:
      dev: t2.micro
      prod: m1.small
    us-east-2: 
      dev: m1.small
      prod: m1.large
  AMIMap:
    us-east-1:
      dev: ami-043a5a82b6cf98947
      prod: ami-043a5a82b6cf98947
    us-east-2:
      dev: ami-006ec002b74f6c066
      prod: ami-006ec002b74f6c066
Parameters: 
  EnvironmentParameter: 
    Type: String
    Default: dev
    AllowedValues: 
      - dev
      - prod
    Description: Enter dev or prod.
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [AMIMap, !Ref "AWS::Region", Ref: EnvironmentParameter]
      InstanceType: !FindInMap [InstanceMap,!Ref "AWS::Region", Ref: EnvironmentParameter]
